Compiler::compileFile("Languages/StateMachines/Mapping/Boot",true,true);
Compiler::compileFile("Languages/StateMachines/Mapping/Java",true,true);
Compiler::compileFile("Languages/StateMachines/Mapping/JavaMapping",true,true);
Compiler::compileFile("Languages/StateMachines/Mapping/XMLMapping",true,true);