import Compiler;

compileFile("Clients/ModelBrowserXCore/Boot",true,true);
compileFile("Clients/ModelBrowserXCore/Manifest",true,true);
compileFile("Clients/ModelBrowserXCore/ModelBrowserXCore",true,true);
compileFile("Clients/ModelBrowserXCore/MappingCreator",true,true);
compileFile("Clients/ModelBrowserXCore/ElementXNode",true,true);
compileFile("Clients/ModelBrowserXCore/ObjectXNode",true,true);
compileFile("Clients/ModelBrowserXCore/ContainerXNode",true,true);
compileFile("Clients/ModelBrowserXCore/ClassXNode",true,true);
compileFile("Clients/ModelBrowserXCore/BrowserTreeMapping",true,true);
compileFile("Clients/ModelBrowserXCore/MappingClient",true,true);
compileFile("Clients/ModelBrowserXCore/ConstructorXNode",true,true);
compileFile("Clients/ModelBrowserXCore/SnapshotXNode",true,true);
compileFile("Clients/ModelBrowserXCore/TableXNode",true,true);
compileFile("Clients/ModelBrowserXCore/DiagramXNode",true,true);
compileFile("Clients/ModelBrowserXCore/SyncableDiagramXNode",true,true);
compileFile("Clients/ModelBrowserXCore/Extensions",true,true);
compileFile("Clients/ModelBrowserXCore/RegistryExtensionPoints",true,true);
