import Compiler;

compileFile("Clients/FileBrowser/Boot",true,true);
compileFile("Clients/FileBrowser/Manifest",true,true);
compileFile("Clients/FileBrowser/DirectoryXNode",true,true);
compileFile("Clients/FileBrowser/FileBrowser",true,true);
compileFile("Clients/FileBrowser/FileHeader",true,true);
compileFile("Clients/FileBrowser/Extensions",true,true);
compileFile("Clients/FileBrowser/RegistryContributions",true,true);
