import Compiler;

compileFile("DocTables/Forms/Boot",true,true);
compileFile("DocTables/Forms/ActiveText",true,true);
compileFile("DocTables/Forms/Form",true,true);
compileFile("DocTables/Forms/FormButton",true,true);
compileFile("DocTables/Forms/FormCheckBox",true,true);
compileFile("DocTables/Forms/FormComboBox",true,true);
compileFile("DocTables/Forms/Forms",true,true);
compileFile("DocTables/Forms/FormTextField",true,true);
compileFile("DocTables/Forms/FormTextArea",true,true);