import Compiler;

compileFile("Clients/MenusLanguages/Boot",true,true);
compileFile("Clients/MenusLanguages/Manifest",true,true);
compileFile("Clients/MenusLanguages/XMap",true,true);
compileFile("Clients/MenusLanguages/Associations",true,true);
compileFile("Clients/MenusLanguages/RegistryContributions",true,true);


