import Compiler;

compileFile("Database/Interfaces/Boot",true,true);
compileFile("Database/Interfaces/Database",true,true);
compileFile("Database/Interfaces/Interfaces",true,true);
compileFile("Database/Interfaces/QueryResult",true,true);