import Compiler;

compileFile("DocTables/EventHandlers/Boot",true,true);
compileFile("DocTables/EventHandlers/EventButton",true,true);
compileFile("DocTables/EventHandlers/EventForm",true,true);
compileFile("DocTables/EventHandlers/EventHandler",true,true);
compileFile("DocTables/EventHandlers/EventHandlers",true,true);
