import Compiler;

compileFile("Clients/DiagramsMapping/Boot",true,true);
compileFile("Clients/DiagramsMapping/DiagramsMapping",true,true);
compileFile("Clients/DiagramsMapping/DiagramStub",true,true);
compileFile("Clients/DiagramsMapping/DiagramContribution",true,true);
compileFile("Clients/DiagramsMapping/ElementXDiagram",true,true);
compileFile("Clients/DiagramsMapping/ElementMap",true,true);
compileFile("Clients/DiagramsMapping/ThemableMap",true,true);
compileFile("Clients/DiagramsMapping/ElementXNode",true,true);
compileFile("Clients/DiagramsMapping/ElementXEdge",true,true);
compileFile("Clients/DiagramsMapping/RegistryExtensionPoints",true,true);
compileFile("Clients/DiagramsMapping/Theme",true,true);
compileFile("Clients/DiagramsMapping/DiagramMappingClient",true,true);
compileFile("Clients/DiagramsMapping/DiagramManager",true,true);
compileFile("Clients/DiagramsMapping/Extensions",true,true);
compileFile("Clients/DiagramsMapping/Manifest",true,true);
