Compiler::compileFile("Aspects/AllAspects",true,true);
Compiler::compileFile("Aspects/Aspect",true,true);
Compiler::compileFile("Aspects/Aspects",true,true);
Compiler::compileFile("Aspects/Boot",true,true);
Compiler::compileFile("Aspects/Class",true,true);
Compiler::compileFile("Aspects/ComponentDef",true,true);
Compiler::compileFile("Aspects/Semantics",true,true);

 