import Compiler;

compileFile("DocTables/HTML/Browser/Boot",true,true);
compileFile("DocTables/HTML/Browser/BrowserDisplayEngine",true,true);
compileFile("DocTables/HTML/Browser/AddHandlers",true,true);