import Compiler;

compileFile("Clients/MappingMapping/MapXNode",true,true);
compileFile("Clients/MappingMapping/DomainXDomainEdge",true,true);
compileFile("Clients/MappingMapping/RangeXRangeEdge",true,true);
compileFile("Clients/MappingMapping/MapXInheritanceEdge",true,true);
compileFile("Clients/MappingMapping/PackageXMappingDiagram",true,true);
compileFile("Clients/MappingMapping/MappingClient",true,true);
compileFile("Clients/MappingMapping/MappingMapping",true,true);
//compileFile("Clients/MappingMapping/ScopeXScopeEdge",true,true);
//compileFile("Clients/MappingMapping/SyncXNode",true,true);
compileFile("Clients/MappingMapping/Boot",true,true);
compileFile("Clients/MappingMapping/Manifest",true,true);
