import Compiler;

compileFile(xmf.homeDir() + "/Clients/Graphs/Boot",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Manifest",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/ColorGenerator",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Graphs",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Line",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Label",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Canvas",true,true);
compileFile(xmf.homeDir() + "/Clients/Graphs/Graph",true,true);