import Compiler;

compileFile("Languages/ClassTool/Boot",true,true);
compileFile("Languages/ClassTool/Manifest",true,true);
compileFile("Languages/ClassTool/ClassTool",true,true);
compileFile("Languages/ClassTool/PackageXClassToolMapping",true,true);
compileFile("Languages/ClassTool/InvokeOp",true,true);