import Compiler;

compileFile(xmf.homeDir() + "/XML/XMI/XMI",true,true);
compileFile(xmf.homeDir() + "/XML/XMI/Boot",true,true);
compileFile(xmf.homeDir() + "/XML/XMI/XMI11Rose",true,true);
compileFile(xmf.homeDir() + "/XML/XMI/XMI12Poseidon",true,true);
compileFile(xmf.homeDir() + "/XML/XMI/EMFXMI",true,true);