import Compiler;

compileFile("Lib/Graphs/Boot",true,true);
compileFile("Lib/Graphs/Edge",true,true);
compileFile("Lib/Graphs/Graph",true,true);
compileFile("Lib/Graphs/Graphs",true,true);
compileFile("Lib/Graphs/Manifest",true,true);
compileFile("Lib/Graphs/Node",true,true);
