import Compiler;

compileFile("Clients/ModelClipboard/ClipboardDef/Boot",true,true);
compileFile("Clients/ModelClipboard/ClipboardDef/Manifest",true,true);
compileFile("Clients/ModelClipboard/ClipboardDef/ClipboardRule",true,true);
compileFile("Clients/ModelClipboard/ClipboardDef/CutRule",true,true);
compileFile("Clients/ModelClipboard/ClipboardDef/CopyRule",true,true);
compileFile("Clients/ModelClipboard/ClipboardDef/PasteRule",true,true);

