Compiler::compileFile("XRules/Syntax/Boot",true,true);
Compiler::compileFile("XRules/Syntax/Condition",true,true);
Compiler::compileFile("XRules/Syntax/And",true,true);
Compiler::compileFile("XRules/Syntax/Or",true,true);
Compiler::compileFile("XRules/Syntax/Pattern",true,true);
Compiler::compileFile("XRules/Syntax/Rule",true,true);
Compiler::compileFile("XRules/Syntax/Syntax",true,true);
