Compiler::compileFile("Mappings/XCoreXSQL/Boot",true,true);
Compiler::compileFile("Mappings/XCoreXSQL/XCoreXSQL",true,true);
Compiler::compileFile("Mappings/XCoreXSQL/TypeXType",true,true);
Compiler::compileFile("Mappings/XCoreXSQL/AttributeXColumn",true,true);
Compiler::compileFile("Mappings/XCoreXSQL/ClassXTable",true,true);