import Compiler;

compileFile("Lib/Stacks/Boot",true,true);
compileFile("Lib/Stacks/Stacks",true,true);
compileFile("Lib/Stacks/Manifest",true,true);
compileFile("Lib/Stacks/Stack",true,true);
compileFile("Lib/Stacks/Queue",true,true);
compileFile("Lib/Stacks/StackUnderflow",true,true);
