import Compiler;

compileFile("Clients/XML/Boot",true,true);
compileFile("Clients/XML/Diagram",true,true);
compileFile("Clients/XML/DiagramXMLFormatter",true,true);
compileFile("Clients/XML/DiagramXMLInflater",true,true);
compileFile("Clients/XML/Manifest",true,true);