import Compiler;

compileFile("Clients/ProjectBrowser/Boot",true,true);
compileFile("Clients/ProjectBrowser/Manifest",true,true);
compileFile("Clients/ProjectBrowser/Diagram",true,true);
compileFile("Clients/ProjectBrowser/Ops",true,true);
compileFile("Clients/ProjectBrowser/Menus",true,true);
compileFile("Clients/ProjectBrowser/ProjectBrowser",true,true);
compileFile("Clients/ProjectBrowser/ProjectXNode",true,true);
compileFile("Clients/ProjectBrowser/RegistryContributions",true,true);