import Compiler;

compileFile("Languages/MicroJava/J2EE/Boot",true,true);
compileFile("Languages/MicroJava/J2EE/Manifest",true,true);
compileFile("Languages/MicroJava/J2EE/ClassToEntityBean",true,true);
compileFile("Languages/MicroJava/J2EE/ClassesToSessionBean",true,true);
compileFile("Languages/MicroJava/J2EE/ConstraintsToJ2EE",true,true);
compileFile("Languages/MicroJava/J2EE/XCoreToJ2EE",true,true);
compileFile("Languages/MicroJava/J2EE/J2EE",true,true);
compileFile("Languages/MicroJava/J2EE/PackageToJ2EE",true,true);
