import Compiler;

compileFile("Clients/OleBridge/MicrosoftExcel/Boot",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/Excel",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/Range",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/Workbook",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/Worksheet",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/Manifest",true,true);
compileFile("Clients/OleBridge/MicrosoftExcel/MicrosoftExcel",true,true);