import Compiler;

compileFile("Interfaces/Boot",true,true);
compileFile("Interfaces/Def",true,true);
compileFile("Interfaces/Interface",true,true);
compileFile("Interfaces/Interfaces",true,true);
compileFile("Interfaces/Property",true,true);
