import Compiler;

compileFile("Clients/PropertyEditorXCore/Boot",true,true);
compileFile("Clients/PropertyEditorXCore/Manifest",true,true);
compileFile("Clients/PropertyEditorXCore/RegistryContributions",true,true);
compileFile("Clients/PropertyEditorXCore/PropertyEditorXCore",true,true);

compileFile("Clients/PropertyEditorXCore/DocumentationTextBox",true,true);
compileFile("Clients/PropertyEditorXCore/DocumentationEditor",true,true);
compileFile("Clients/PropertyEditorXCore/AbstractObjectEditor",true,true);
compileFile("Clients/PropertyEditorXCore/ObjectPE",true,true);
compileFile("Clients/PropertyEditorXCore/ObjectXForm",true,true);
compileFile("Clients/PropertyEditorXCore/DependencyXForm",true,true);

compileFile("Clients/PropertyEditorXCore/CompiledOperationSourceTextBox",true,true);
compileFile("Clients/PropertyEditorXCore/CompiledOperationSourceEditor",true,true);
compileFile("Clients/PropertyEditorXCore/CompiledOperationSelfTextField",true,true);
compileFile("Clients/PropertyEditorXCore/CompiledOperationPE",true,true);
compileFile("Clients/PropertyEditorXCore/CompiledOperationXForm",true,true);

compileFile("Clients/PropertyEditorXCore/ConstraintSourceTextBox",true,true);
compileFile("Clients/PropertyEditorXCore/ConstraintSourceEditor",true,true);
compileFile("Clients/PropertyEditorXCore/ConstraintPE",true,true);
compileFile("Clients/PropertyEditorXCore/ConstraintXForm",true,true);

compileFile("Clients/PropertyEditorXCore/ConstructorSourceTextBox",true,true);
compileFile("Clients/PropertyEditorXCore/ConstructorSourceEditor",true,true);
compileFile("Clients/PropertyEditorXCore/ConstructorNamesTextField",true,true);
compileFile("Clients/PropertyEditorXCore/ConstructorPE",true,true);
compileFile("Clients/PropertyEditorXCore/ConstructorXForm",true,true);

compileFile("Clients/PropertyEditorXCore/XMapClauseTextBox",true,true);
compileFile("Clients/PropertyEditorXCore/XMapClauseSelfTextField",true,true);
compileFile("Clients/PropertyEditorXCore/XMapClauseCodeComboBox",true,true);
compileFile("Clients/PropertyEditorXCore/XMapMapPE",true,true);
compileFile("Clients/PropertyEditorXCore/XMapMapXForm",true,true);
compileFile("Clients/PropertyEditorXCore/XMapClausePE",true,true);
compileFile("Clients/PropertyEditorXCore/XMapClauseXForm",true,true);

compileFile("Clients/PropertyEditorXCore/GrammarClauseCodeComboBox",true,true);
compileFile("Clients/PropertyEditorXCore/GrammarPE",true,true);
compileFile("Clients/PropertyEditorXCore/GrammarXForm",true,true);

compileFile("Clients/PropertyEditorXCore/MappingClient",true,true);
