import Compiler;

compileFile("Clients/ModelBrowsers/Boot",true,true);
compileFile("Clients/ModelBrowsers/Manifest",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowserEventHandler",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowserCommandInterpreter",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowserClient",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowserIdError",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowsers",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowser",true,true);
compileFile("Clients/ModelBrowsers/Dummy",true,true);
compileFile("Clients/ModelBrowsers/ModelBrowserNode",true,true);
compileFile("Clients/ModelBrowsers/AbstractMappingClient",true,true);
compileFile("Clients/ModelBrowsers/Extensions",true,true);
compileFile("Clients/ModelBrowsers/RegistryExtensionPoints",true,true);