import Compiler;

compileFile("Clients/ToolDeployment/Boot",true,true);
compileFile("Clients/ToolDeployment/BrandingProperty",true,true);
compileFile("Clients/ToolDeployment/DefaultToolDeployer",true,true);
compileFile("Clients/ToolDeployment/DeployedToolDescriptor",true,true);
compileFile("Clients/ToolDeployment/Manifest",true,true);
compileFile("Clients/ToolDeployment/ToolDeployer",true,true);
compileFile("Clients/ToolDeployment/ToolDeployment",true,true);