import Compiler;

compileFile("Undo/Boot",true,true);
compileFile("Undo/Manifest",true,true);
compileFile("Undo/Undo",true,true);
compileFile("Undo/UndoEngine",true,true);
compileFile("Undo/UndoStackListener",true,true);
compileFile("Undo/UndoExecutionListener",true,true);
compileFile("Undo/Contribution",true,true);
compileFile("Undo/Undoable",true,true);



