import Compiler;

compileFile("Clients/XmfTextEditor/Boot",true,true);
compileFile("Clients/XmfTextEditor/Manifest",true,true);
compileFile("Clients/XmfTextEditor/XmfTextEditor",true,true);
compileFile("Clients/XmfTextEditor/FileEditor",true,true);
compileFile("Clients/XmfTextEditor/RegistryContributions",true,true);