import Compiler;

compileFile("Clients/ExceptionReport/Boot",true,true);
compileFile("Clients/ExceptionReport/Manifest",true,true);
compileFile("Clients/ExceptionReport/ExceptionReport",true,true);
compileFile("Clients/ExceptionReport/ExceptionNode",true,true);
compileFile("Clients/ExceptionReport/ArgNode",true,true);
compileFile("Clients/ExceptionReport/LocalNode",true,true);
compileFile("Clients/ExceptionReport/FrameNode",true,true);
compileFile("Clients/ExceptionReport/ResourceNode",true,true);
compileFile("Clients/ExceptionReport/OperationNode",true,true);
compileFile("Clients/ExceptionReport/SelfNode",true,true);
compileFile("Clients/ExceptionReport/ReportTree",true,true);
compileFile("Clients/ExceptionReport/ExceptionForm",true,true);