import Compiler;

compileFile("Languages/MicroJava/Expressions/Boolean",true,true);
compileFile("Languages/MicroJava/Expressions/BinExp",true,true);
compileFile("Languages/MicroJava/Expressions/Boot",true,true);
compileFile("Languages/MicroJava/Expressions/JExp",true,true);
compileFile("Languages/MicroJava/Expressions/Cast",true,true);
compileFile("Languages/MicroJava/Expressions/Expressions",true,true);
compileFile("Languages/MicroJava/Expressions/FieldRef",true,true);
compileFile("Languages/MicroJava/Expressions/Float",true,true);
compileFile("Languages/MicroJava/Expressions/Int",true,true);
compileFile("Languages/MicroJava/Expressions/Manifest",true,true);
compileFile("Languages/MicroJava/Expressions/New",true,true);
compileFile("Languages/MicroJava/Expressions/Send",true,true);
compileFile("Languages/MicroJava/Expressions/This",true,true);
compileFile("Languages/MicroJava/Expressions/JString",true,true);
compileFile("Languages/MicroJava/Expressions/UnExp",true,true);
compileFile("Languages/MicroJava/Expressions/Update",true,true);
compileFile("Languages/MicroJava/Expressions/Var",true,true);
