import Compiler;

compileFile("Languages/Commands/Diagrams/Boot",true,true);
compileFile("Languages/Commands/Diagrams/CommandDiagram",true,true);
compileFile("Languages/Commands/Diagrams/Diagrams",true,true);
compileFile("Languages/Commands/Diagrams/BlockNode",true,true);
compileFile("Languages/Commands/Diagrams/GuardNode",true,true);
compileFile("Languages/Commands/Diagrams/SkipNode",true,true);
compileFile("Languages/Commands/Diagrams/FalseEdge",true,true);
compileFile("Languages/Commands/Diagrams/NextEdge",true,true);
compileFile("Languages/Commands/Diagrams/TrueEdge",true,true);
compileFile("Languages/Commands/Diagrams/Statement",true,true);
compileFile("Languages/Commands/Diagrams/TypeDecNode",true,true);
compileFile("Languages/Commands/Diagrams/ValueDecNode",true,true);
compileFile("Languages/Commands/Diagrams/C",true,true);
compileFile("Languages/Commands/Diagrams/Pn",true,true);
compileFile("Languages/Commands/Diagrams/W",true,true);
