import Compiler;

compileFile("Lib/Arrays/Boot",true,true);
compileFile("Lib/Arrays/Arrays",true,true);
compileFile("Lib/Arrays/Manifest",true,true);
compileFile("Lib/Arrays/Simple2DArray",true,true);
compileFile("Lib/Arrays/Expandable2DArray",true,true);
compileFile("Lib/Arrays/ArrayIndexOutOfBounds",true,true);
compileFile("Lib/Arrays/Extensions",true,true);
