import Compiler;

compileFile("Protect/Boot",true,true);
compileFile("Protect/Manifest",true,true);
compileFile("Protect/NameSpaceCheck",true,true);
compileFile("Protect/ProtectView",true,true);
compileFile("Protect/ProtectDelete",true,true);