import Compiler;

compileFile(xmf.homeDir() + "/Clients/DropDownMenus/Boot",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenus",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/AbstractMenu",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenu",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenuItem",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenuGroup",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenuAction",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/DropDownMenuClient",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/RegistryExtensionPoints",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/Manifest",true,true);
compileFile(xmf.homeDir() + "/Clients/DropDownMenus/XMF",true,true);
