import Compiler;

compileFile("Clients/Undo/Boot",true,true);
compileFile("Clients/Undo/Manifest",true,true);
compileFile("Clients/Undo/Undo",true,true);
compileFile("Clients/Undo/UndoClient",true,true);
compileFile("Clients/Undo/UndoCommandInterpreter",true,true);
compileFile("Clients/Undo/UndoEventHandler",true,true);



