Compiler::compileFile("Doc/HTML/Boot",true,true);
Compiler::compileFile("Doc/HTML/Preferences",true,true);
Compiler::compileFile("Doc/HTML/ToHTML",true,true);
Compiler::compileFile("Doc/HTML/ConstraintReport",true,true);
Compiler::compileFile("Doc/HTML/String",true,true);
