import Compiler;

compileFile("Clients/OleBridge/MicrosoftWord/Boot",true,true);
compileFile("Clients/OleBridge/MicrosoftWord/Document",true,true);
compileFile("Clients/OleBridge/MicrosoftWord/MicrosoftWord",true,true);
compileFile("Clients/OleBridge/MicrosoftWord/Manifest",true,true);
compileFile("Clients/OleBridge/MicrosoftWord/Word",true,true);