import Compiler;

compileFile("Clients/LiveDocViewer/Boot",true,true);
compileFile("Clients/LiveDocViewer/Manifest",true,true);
compileFile("Clients/LiveDocViewer/LiveDocViewer",true,true);
compileFile("Clients/LiveDocViewer/Viewer",true,true);