import Compiler;

compileFile("Languages/Automata/Automata",true,true);
compileFile("Languages/Automata/Automaton",true,true);
compileFile("Languages/Automata/Boot",true,true);
compileFile("Languages/Automata/Inspect",true,true);
compileFile("Languages/Automata/Manifest",true,true);
compileFile("Languages/Automata/State",true,true);
compileFile("Languages/Automata/Transition",true,true);
