Compiler::compileFile("Walkers/TypeChecker/Elements/Boot",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/Class",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/CompiledOperation",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/Constraint",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/Package",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/TypeCheckClass",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/TypeCheckConstraint",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/TypeCheckOperation",true,true);
Compiler::compileFile("Walkers/TypeChecker/Elements/TypeCheckPackage",true,true);
 