import Compiler;

compileFile("Clients/PackageTextEditor/Boot",true,true);
compileFile("Clients/PackageTextEditor/Manifest",true,true);
compileFile("Clients/PackageTextEditor/PackageTextEditor",true,true);
compileFile("Clients/PackageTextEditor/PackageEditor",true,true);