import Compiler;

compileFile("Clients/ReportConstraint/Boot",true,true);
compileFile("Clients/ReportConstraint/Manifest",true,true);
compileFile("Clients/ReportConstraint/ReportConstraint",true,true);
compileFile("Clients/ReportConstraint/ReportNode",true,true);
compileFile("Clients/ReportConstraint/ReportTree",true,true);
compileFile("Clients/ReportConstraint/Report",true,true);