import Compiler;

compileFile("Languages/Processes/Boot",true,true);
compileFile("Languages/Processes/Manifest",true,true);
compileFile("Languages/Processes/Processes",true,true);
compileFile("Languages/Processes/Process",true,true);
compileFile("Languages/Processes/ProcessStep",true,true);