import Compiler;

compileFile("Clients/BrowserInterface/Displays/Boot",true,true);
compileFile("Clients/BrowserInterface/Displays/Add",true,true);
compileFile("Clients/BrowserInterface/Displays/Display",true,true);
compileFile("Clients/BrowserInterface/Displays/Displays",true,true);
compileFile("Clients/BrowserInterface/Displays/Navigate",true,true);
compileFile("Clients/BrowserInterface/Displays/Literal",true,true);
