import Compiler;

compileFile("Clients/DialogBoxes/Boot",true,true);
compileFile("Clients/DialogBoxes/Manifest",true,true);
compileFile("Clients/DialogBoxes/DialogBoxes",true,true);
compileFile("Clients/DialogBoxes/DialogCommandInterpreter",true,true);
compileFile("Clients/DialogBoxes/DialogEventHandler",true,true);
compileFile("Clients/DialogBoxes/BusyDialog",true,true);
compileFile("Clients/DialogBoxes/ColorDialog",true,true);
compileFile("Clients/DialogBoxes/FontDialog",true,true);
compileFile("Clients/DialogBoxes/MessageDialog",true,true);
compileFile("Clients/DialogBoxes/WarningDialog",true,true);
compileFile("Clients/DialogBoxes/ErrorDialog",true,true);
compileFile("Clients/DialogBoxes/QuestionDialog",true,true);
compileFile("Clients/DialogBoxes/ConfirmDialog",true,true);
compileFile("Clients/DialogBoxes/MultioptionDialog",true,true);
compileFile("Clients/DialogBoxes/FileDialog",true,true);
compileFile("Clients/DialogBoxes/InputDialog",true,true);
compileFile("Clients/DialogBoxes/OrderingDialog",true,true);
compileFile("Clients/DialogBoxes/OrderingDialog2",true,true);
compileFile("Clients/DialogBoxes/DirectoryDialog",true,true);
compileFile("Clients/DialogBoxes/SelectionDialog",true,true);
compileFile("Clients/DialogBoxes/ProgressDialog",true,true);
compileFile("Clients/DialogBoxes/TextAreaDialog",true,true);
compileFile("Clients/DialogBoxes/DialogBoxClient",true,true);
compileFile("Clients/DialogBoxes/TreeDialog",true,true);



