Compiler::compileFile(xmf.homeDir() + "/Boot/Server/Boot",true,true);
Compiler::compileFile(xmf.homeDir() + "/Boot/Server/BootEnterprise",true,true);
Compiler::compileFile(xmf.homeDir() + "/Boot/Server/ClientManager",true,true);