import Compiler;

compileFile("Languages/Commands/Mapping/Boot",true,true);
compileFile("Languages/Commands/Mapping/Diagram",true,true);
compileFile("Languages/Commands/Mapping/Mapping",true,true);
