import Compiler;

compileFile("Assembler/Assembler",true,true);
compileFile("Assembler/Boot",true,true);
compileFile("Assembler/CodeBox",true,true);
compileFile("Assembler/Manifest",true,true);
