import Compiler;

compileFile("Clients/SnapshotMapping/Boot",true,true);
compileFile("Clients/SnapshotMapping/Manifest",true,true);
compileFile("Clients/SnapshotMapping/SnapshotMapping",true,true);
compileFile("Clients/SnapshotMapping/DependencyNameXText",true,true);
compileFile("Clients/SnapshotMapping/DependencyXDependencyEdge",true,true);
compileFile("Clients/SnapshotMapping/DocXNote",true,true);
compileFile("Clients/SnapshotMapping/ObjectXNode",true,true);
compileFile("Clients/SnapshotMapping/SlotXEdge",true,true);
compileFile("Clients/SnapshotMapping/SetValueXEdge",true,true);
compileFile("Clients/SnapshotMapping/SlotXText",true,true);
compileFile("Clients/SnapshotMapping/SnapshotXSnapshotDiagram",true,true);
compileFile("Clients/SnapshotMapping/MappingClient",true,true);
compileFile("Clients/SnapshotMapping/MenuOperations",true,true);
compileFile("Clients/SnapshotMapping/RegistryContributions",true,true);
compileFile("Clients/SnapshotMapping/OrderSequence",true,true);
// compileFile("Clients/SnapshotMapping/SnapshotTheme1",true,true);
