import Compiler;

compileFile("Comms/Boot",true,true);
compileFile("Comms/Client",true,true);
compileFile("Comms/Comms",true,true);
compileFile("Comms/Manifest",true,true);
compileFile("Comms/Server",true,true);