import Compiler;

compileFile("DocTables/HTML/InternalBrowser/Boot",true,true);
compileFile("DocTables/HTML/InternalBrowser/InternalBrowser",true,true);
compileFile("DocTables/HTML/InternalBrowser/InternalDisplayEngine",true,true);